blank_issues_enabled: false
contact_links:
  - name: Ideas and questions
    url: https://github.com/dmrock/deutscherl/discussions
    about: Suggest a topic or a feature, or ask a question in GitHub Discussions.
